
favicon:
  enable: true
  icon: /images/favicon.ico
  touch_icon: /images/favicon.ico

# Google Analytics
gtag:
  enable: false
  gtagkey: UA-126364107-1

# gitalk comments
gitalk:
  enable: false
  clientID: 57fd80ca85f9d3276439
  clientSecret: 7411553827815e5766ebe0bce5e4fb2e36e3217f
  repo: blog
  owner: zchengsite
  admin: zchengsite
  distractionFreeMode: false

# 用户头像与昵称
avatar:
  author_photo: /images/34339465.jpg
  author_nickname: Oranges

# 导航信息
navbar:
  -
    name: 主页
    path: /
  -
    name: 归档
    path: /archives/
  -
    name: 标签
    path: /tags/
  -
    name: 朋友
    path: /friends/
  -
    name: 关于我
    path: /about/


# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Ayu
    site: https://yuang.site
    meta:
  -
    nickname: Lxwu
    site: https://lxwu.me
    meta:
  -
    nickname: Mhyu
    site: https://mhyu.top
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: email
      icon: envelope
      path: Mailto:ghsau@163.com
    -
      name: facebook
      icon: facebooksquare
      path:
    -
      name: twitter
      icon: twitter
      path:
    -
      name: 微信
      icon: wechat
      path:
    -
      name: 微博
      icon: weibo
      path:

  more:
    -
      name: Theme - oranges | Orange's blog
      path: https://github.com/zchengsite/hexo-theme-oranges
