
favicon:
  enable: true
  icon: /images/favicon.ico
  touch_icon: /images/favicon.ico

# Google Analytics
gtag:
  enable: false
  gtagkey: UA-126364107-1

# gitalk comments
gitalk:
  enable: false
  clientID: 57fd80ca85f9d3276439
  clientSecret: 7411553827815e5766ebe0bce5e4fb2e36e3217f
  repo: blog
  owner: zchengsite
  admin: zchengsite
  distractionFreeMode: false

# 友链详细信息：支持多个友链
friends:
  -
    nickname: Ayu # 昵称
    site: https://yuang.site # 站点地址
    meta: # 站点描述
  -
    nickname: Lxwu # 昵称
    site: https://lxwu.me # 站点地址
    meta: # 站点描述
  -
    nickname: Mhyu
    site: https://mhyu.top
    meta:
