
favicon:
  enable: true
  icon: /username.github.io/images/favicon.ico
  touch_icon: /username.github.io/images/favicon.ico

# RSS文件位置
rss:

# Google Analytics
gtag:
  enable: false
  gtagkey: 

# gitalk comments
gitalk:
  enable: false
  clientID: 
  clientSecret: 
  repo: 
  owner: 
  admin: 
  distractionFreeMode: false

# 用户头像与昵称
avatar:
  author_photo: /username.github.io/images/34339465.jpg
  author_nickname: Oranges

# 导航信息
navbar:
  -
    name: 主页
    enable: true
    path: /username.github.io/
  -
    name: 归档
    enable: true
    path: /username.github.io/archives/
  -
    name: 分类
    enable: true
    path: /username.github.io/categories/
  -
    name: 标签
    enable: true
    path: /username.github.io/tags/
  -
    name: 朋友
    enable: true
    path: /username.github.io/friends/
  -
    name: 关于我
    enable: true
    path: /username.github.io/about/

# 文章目录
catalog:
  enable: true

# 友链详细信息：支持多个友链
friends:
  # nickname: 昵称
  # site: 地址
  # meta: 描述
  -
    nickname: Google
    site: https://www.google.com/
    meta:

# 页脚信息
footer:
  # social: 社交方式
  # more: 更多页脚信息
  social:
    # name: 名称
    # icon: 图标，目前仅支持IconFont部分图标
    # path: 地址
    -
      name: github
      icon: github
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: email
      icon: envelope
      path: mscsdfsaw***@163.com
    -
      name: facebook
      icon: facebooksquare
      path:
    -
      name: twitter
      icon: twitter
      path:
    -
      name: 微信
      icon: wechat
      path:
    -
      name: 微博
      icon: weibo
      path:

  more:
    -
      name: Copyright © Oranges 2020
      path: https://github.com/zchengsite/hexo-theme-oranges
    -
      name: Theme by Oranges | Powered by Hexo
      path: https://github.com/zchengsite/hexo-theme-oranges
